# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  source = "https://github.com/sirupsen/logrus.git"
  version = "0.11.5"

[[constraint]]
  name = "github.com/evalphobia/logrus_sentry"
  version = "0.2.12"

[[constraint]]
  name = "github.com/getsentry/raven-go"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "0.8.1"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/mesos/mesos-go"
  revision = "36b30d8a146d425c9cbd70afe86f667540a248e3"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.16.12"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision = "f6abca593680b2315d2075e0f5e2a9751e3f431a"

[[constraint]]
  name = "gopkg.in/h2non/gentleman.v1"
  version = "1.0.3"
